name: Lint

on: push

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'skip_ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip nox
      - run: nox -s lint
